services:
  - type: web
    name: barberia-system
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
    startCommand: gunicorn barberia_system.wsgi:application --bind 0.0.0.0:$PORT
    autoDeploy: true