# Generated by Django 6.0.3 on 2026-03-06 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barberia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='barbero',
            name='telefono',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cita',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
