# Generated by Django 6.0.3 on 2026-03-06 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barberia', '0002_barbero_telefono_alter_cita_precio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cita',
            options={'ordering': ['fecha', 'hora']},
        ),
        migrations.RemoveField(
            model_name='barbero',
            name='telefono',
        ),
        migrations.AlterField(
            model_name='cita',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterUniqueTogether(
            name='cita',
            unique_together={('barbero', 'fecha', 'hora')},
        ),
    ]
